language: objective-c
osx_image: xcode7.3
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - brew outdated carthage || brew upgrade carthage
before_script:
  - carthage bootstrap --no-build
script:
  - xctool -workspace Postal.xcworkspace -scheme Postal-iOS -sdk iphonesimulator9.3 build
  - xctool -workspace Postal.xcworkspace -scheme Postal-macOS -sdk macosx10.11 build
